language: go

go:
- 1.7
- 1.8
- master

matrix:
  allow_failures:
  - go: master 

go_import_path: github.com/redhat-developer/opencompose

before_install:
- go get golang.org/x/tools/cmd/goimports
- go get github.com/Masterminds/glide
- go get github.com/sgotti/glide-vc
- go get github.com/golang/lint/golint

install:
- true

script:
- make -j64 test
- make -j64 install
- make -j64 checks

notifications:
  email: false
